version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phoenix_app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d phoenix_app"]
      interval: 5s
      timeout: 5s
      retries: 20

  phoenix:
    build: ./phoenix-api
    working_dir: /app
    volumes:
      - ./phoenix-api:/app
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/phoenix_app
      SECRET_KEY_BASE: dev_secret_key_base_change_me
      PHX_HOST: localhost
      PORT: "4000"
      IMPORT_TOKEN: dev-import-token
      PESEL_FIRSTNAMES_DATASET_ID: "1667"
      PESEL_SURNAMES_DATASET_ID: "1681"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  symfony:
    build: ./symfony-app
    volumes:
      - ./symfony-app:/app
    environment:
      PHOENIX_BASE_URL: http://phoenix:4000/api
    depends_on:
      - phoenix
    ports:
      - "8000:8000"
