parameters:
    phoenix_base_url: '%env(string:PHOENIX_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Makes classes in src/ available as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Bind the interface to the concrete client
    App\Api\PhoenixApiClientInterface: '@App\Api\PhoenixApiClient'

    # Configure the concrete client
    App\Api\PhoenixApiClient:
        arguments:
            $baseUrl: '%phoenix_base_url%'
